/**
 * The scripted safeguarding message.
 *
 * This exact string is the only thing any surface ever renders when an
 * escalation is raised. It is never reworded, never generated by a model at the
 * point of display, and never varied by which path triggered it — the "I need
 * help" button and passive detection produce the identical sentence.
 *
 * The API deliberately returns a boolean and nothing else, so there is no
 * transport by which model output could reach this text.
 */
export const DISTRESS_SCRIPTED_MESSAGE =
  "Your teacher has been notified and will follow up with you.";

/**
 * How the escalation was raised. Both produce the same message to the student;
 * the distinction exists so a teacher reviewing the record later can tell
 * direct outreach from passive detection.
 */
export type DetectionMethod = "passive_pattern" | "student_initiated";

/** Every Student free-text surface, per Requirement 18.1. */
export type DistressSurface =
  | "practice_ask"
  | "practice_answer"
  | "practice_rubric"
  | "today_ask"
  | "learn_ask"
  | "progress_ask"
  | "need_help_button";

export const DISTRESS_SURFACES: DistressSurface[] = [
  "practice_ask",
  "practice_answer",
  "practice_rubric",
  "today_ask",
  "learn_ask",
  "progress_ask",
  "need_help_button",
];

export interface EscalationRecord {
  id: string;
  createdAt: string;
  student: string;
  method: DetectionMethod;
  surface: DistressSurface;
  text: string | null;
  /**
   * True when the classifier could not give a verdict and the request took the
   * fail-open path. The escalation is real either way; this only tells a
   * reviewer that a model did not confirm it.
   */
  classifierFailed: boolean;
}

export interface DistressResponse {
  escalated: boolean;
}
